export const projects = [
  {
    title: 'Host Your Site',
    description: "A fictional hosting website created using modern CSS techniques like CSS Grid, Flexbox, psuedo selectors and more. Deployed on Netlify with its inbuilt form functionality.",
    image: '/images/hostYourSite.png',
    tags: ['Html', 'Css'],
    source: 'https://github.com/msram1002/hostYourSite',
    visit: 'https://srm-host-your-site.netlify.app/',
    id: 1,
  },
  {
    title: 'Travel Page',
    description: "A fictional travel page with a background video. Glassmorphism was used to style the page to create a frosted glass aesthetic.",
    image: '/images/travelVideo.png',
    tags: ['Html', 'Css'],
    source: 'https://github.com/msram1002/responsive-glassmorphism',
    visit: 'https://ram-travel-landingpage.netlify.app/',
    id: 2,
  },
  {
    title: 'SRM Beats',
    description: "A responsive headphones landing page with dark interface and animated using scroll reveal. Developed first with the Mobile First methodology, then for desktop.",
    image: '/images/srmHeadPhones.png',
    tags: ['Html', 'Css', 'JavaScript'],
    source: 'https://github.com/msram1002/responsive-landingpage-headphones',
    visit: 'https://srm-headphones.netlify.app',
    id: 3,
  },
  {
    title: 'Furniture Store',
    description:"A fictional furniture store developed using JavaScript.",
    image: '/images/jsShopping.png',
    tags: ['Html', 'Css', 'JavaScript'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/comfyandCozyHouseProj',
    visit: 'https://ram-furniture-collection.netlify.app/',
    id: 4,
  },
  {
    title: 'Netflix Clone',
    description: "A sample clone of the dashboard of netflix using React and deployed on Firebase.",
    image: '/images/netflixClone.png',
    tags: ['React', 'Firebase'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/ram-netlfix-clone',
    visit: 'https://ram-netflix-clone.web.app/',
    id: 5,
  },
  {
    title: 'E-Commerce App',
    description: "End to end e-commerce web application created using React, Material UI, Commerce.js and Stripe.",
    image: '/images/srmECommerce.png',
    tags: ['React', 'CommerceJS', 'Stripe'],
    source: 'https://github.com/msram1002/react-ecommerce',
    visit: 'https://ram-srmecommerce.netlify.app/',
    id: 6,
  },
  {
    title: 'SRM Fitness',
    description: 'A fictional fitness website utilizing GreenSock for the animation part.',
    image: '/images/srmFitness.png',
    tags: ['Html', 'Css', 'JavaScript', 'GreenSock'],
    source: 'https://github.com/msram1002/srmFitness',
    visit: 'https://ram-srmfitness.netlify.app/',
    id: 7,
  },
  {
    title: 'Budget Calculator',
    description: 'Creating a budget just got easier! Use this budget calculator and take control of your spending.',
    image: '/images/budgetCalc.png',
    tags: ['Angular', 'Firebase'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/budget-calc-app',
    visit: 'https://ram-budget-calculator.web.app/',
    id: 8,
  },
  {
    title: 'Weather App',
    description: 'A Weather application developed as a Progressive Web App (PWA) and audited by Google Lighthouse.',
    image: '/images/weatherPwa.png',
    tags: ['React'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/pwa-react',
    visit: 'https://ram-pwa-weatherapp.netlify.app/',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];