export const projects = [
  {
    title: 'Travel Page',
    description: "A fictional travel page with a background video. Glassmorphism was used to style the page to create a frosted glass aesthetic.",
    image: '/images/travelVideo.png',
    tags: ['Html', 'Css'],
    source: 'https://github.com/msram1002/responsive-glassmorphism',
    visit: 'https://ram-travel-landingpage.netlify.app/',
    id: 0,
  },
  {
    title: 'Furniture Store',
    description:"A fictional furniture store developed using JavaScript.",
    image: '/images/jsShopping.png',
    tags: ['JavaScript'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/comfyandCozyHouseProj',
    visit: 'https://ram-furniture-collection.netlify.app/',
    id: 1,
  },
  {
    title: 'Netflix Clone',
    description: "A sample clone of the dashboard of netflix using React and deployed on Firebase.",
    image: '/images/netflixClone.jpg',
    tags: ['React', 'Firebase'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/ram-netlfix-clone',
    visit: 'https://ram-netflix-clone.web.app/',
    id: 2,
  },
  {
    title: 'E-Commerce App',
    description: "End to end e-commerce web application created using React, Material UI, Commerce.js and Stripe.",
    image: '/images/srmECommerce.jpg',
    tags: ['React'],
    source: 'https://github.com/msram1002/react-ecommerce',
    visit: 'https://ram-srmecommerce.netlify.app/',
    id: 3,
  },
  {
    title: 'SRM Fitness',
    description: 'A fictional fitness website utilizing GreenSock for the animation part.',
    image: '/images/srmFitness.jpg',
    tags: ['JavaScript'],
    source: 'https://github.com/msram1002/srmFitness',
    visit: 'https://ram-srmfitness.netlify.app/',
    id: 4,
  },
  {
    title: 'Budget Calculator',
    description: 'Creating a budget just got easier! Use this budget calculator and take control of your spending.',
    image: '/images/budgetCalc.jpg',
    tags: ['Angular'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/budget-calc-app',
    visit: 'https://ram-budget-calculator.web.app/',
    id: 5,
  },
  {
    title: 'Weather App - PWA',
    description: 'A Weather application developed as a Progressive Web App (PWA) and audited by Google Lighthouse.',
    image: '/images/weatherPwa.jpg',
    tags: ['React'],
    source: 'https://github.com/msram1002/myProjects/tree/gh-pages/proj/pwa-react',
    visit: 'https://ram-pwa-weatherapp.netlify.app/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];